name: "ci workflow"
on:
  push:
    branches:
      - master
jobs:
  determine-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: "starting ci workflow"
        run: echo "starting ci workflow"
jobs:
  check changes:
    runs-on: ubuntu-latest
    steps:
      - name: "checking for changes"
        run: echo "checking for changes"
